openapi: 3.0.0
info:
  title: "Divideite"
  description: "Divideite API "
  contact:
    url: "/dvp/"
  version: "1.0.1"
servers:
- url: "/dvp/"
paths:
  /ringthebell:
    description: "Attempt a login with this end point"
    post:
      tags:
      - ""
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              title: "request_body"
              type: "object"
              $ref: "#/components/schemas/LoginRequest"
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                type: "custom_model"
                description: ""
                $ref: "#/components/schemas/LoginResponse"
        401:
          description: ""
          content:
            application/json:
              schema:
                type: "custom_model"
                description: ""
                $ref: "#/components/schemas/InvalidLogin"
  /onboard/gatepass:
    description: "Get a temporary session for using signup "
    get:
      tags:
      - ""
      parameters: []
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                type: "string"
                description: ""
        401:
          description: ""
          content:
            application/json:
              schema:
                type: "string"
                description: ""
  /onboard/entry/{user_id}/:
    description: "Create a new user in divideite platform"
    post:
      tags:
      - ""
      parameters:
      - name: "user_id"
        in: "path"
        required: true
        schema:
          type: "string"
          example: "bobdylan01"
        example: "bobdylan01"
      requestBody:
        content:
          application/json:
            schema:
              title: "request_body"
              type: "object"
              $ref: "#/components/schemas/SignupRequest"
      responses:
        200:
          description: ""
          content:
            application/json:
              schema:
                type: "object"
                description: ""
                $ref: "#/components/schemas/LoginResponse"
        403:
          description: ""
          content:
            application/json:
              schema:
                type: "string"
                description: ""
components:
  schemas:
    LoginResponse:
      type: "object"
      properties:
        door_status:
          title: "door_status"
          type: "string"
          description: "Door opened?"
          example: ""
      description: ""
    LoginRequest:
      type: "object"
      properties:
        uid:
          title: "uid"
          type: "string"
          description: ""
          example: "bobdylan01"
        pw:
          title: "pw"
          type: "string"
          description: ""
          example: "my_password"
        extend:
          title: "extend"
          type: "boolean"
          description: ""
          example: true
      description: ""
    InvalidLogin:
      type: "object"
      properties:
        error:
          title: "error"
          type: "string"
          description: ""
          example: ""
      description: ""
    SignupRequest:
      type: "object"
      properties:
        fn:
          title: "fn"
          type: "string"
          description: "First name of the user"
          example: "Bob"
        ln:
          title: "ln"
          type: "string"
          description: ""
          example: "Dylan"
        uid:
          title: "uid"
          type: "string"
          description: ""
          example: "bobdylan01"
        em:
          title: "em"
          type: "string"
          description: ""
          example: "bob@gmail.com"
        dob:
          title: "dob"
          type: "string"
          description: ""
          example: "03/04/1986"
        pw:
          title: "pw"
          type: "string"
          description: ""
          example: "my_password"
        addr:
          title: "addr"
          type: "string"
          description: ""
          example: "Avenue Road, NJ"
        mob:
          title: "mob"
          type: "string"
          description: ""
          example: "+177789225547"
      description: ""
  
